# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5_DesignFile_ExportTarget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Export_Target(object):
    def setupUi(self, Export_Target):
        Export_Target.setObjectName("Export_Target")
        Export_Target.resize(720, 84)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Export_Target.sizePolicy().hasHeightForWidth())
        Export_Target.setSizePolicy(sizePolicy)
        Export_Target.setMinimumSize(QtCore.QSize(720, 84))
        Export_Target.setMaximumSize(QtCore.QSize(3000, 84))
        self.gridLayout = QtWidgets.QGridLayout(Export_Target)
        self.gridLayout.setObjectName("gridLayout")
        self.status_filePath = QtWidgets.QLineEdit(Export_Target)
        self.status_filePath.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_filePath.sizePolicy().hasHeightForWidth())
        self.status_filePath.setSizePolicy(sizePolicy)
        self.status_filePath.setObjectName("status_filePath")
        self.gridLayout.addWidget(self.status_filePath, 0, 1, 1, 1)
        self.pbn_FileExplorer = QtWidgets.QPushButton(Export_Target)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbn_FileExplorer.sizePolicy().hasHeightForWidth())
        self.pbn_FileExplorer.setSizePolicy(sizePolicy)
        self.pbn_FileExplorer.setMaximumSize(QtCore.QSize(120, 30))
        self.pbn_FileExplorer.setObjectName("pbn_FileExplorer")
        self.gridLayout.addWidget(self.pbn_FileExplorer, 0, 0, 1, 1)
        self.pbn_Export = QtWidgets.QPushButton(Export_Target)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbn_Export.sizePolicy().hasHeightForWidth())
        self.pbn_Export.setSizePolicy(sizePolicy)
        self.pbn_Export.setObjectName("pbn_Export")
        self.gridLayout.addWidget(self.pbn_Export, 1, 0, 1, 1)

        self.retranslateUi(Export_Target)
        QtCore.QMetaObject.connectSlotsByName(Export_Target)

    def retranslateUi(self, Export_Target):
        _translate = QtCore.QCoreApplication.translate
        Export_Target.setWindowTitle(_translate("Export_Target", "Dialog"))
        self.pbn_FileExplorer.setText(_translate("Export_Target", "File Path..."))
        self.pbn_Export.setText(_translate("Export_Target", "Export Tags"))
