# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5_DesignFile_ExportTarget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportForm(object):
    def setupUi(self, ExportForm):
        ExportForm.setObjectName("ExportForm")
        ExportForm.resize(720, 84)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExportForm.sizePolicy().hasHeightForWidth())
        ExportForm.setSizePolicy(sizePolicy)
        ExportForm.setMinimumSize(QtCore.QSize(720, 84))
        ExportForm.setMaximumSize(QtCore.QSize(3000, 84))
        self.gridLayout = QtWidgets.QGridLayout(ExportForm)
        self.gridLayout.setObjectName("gridLayout")
        self.status_filePath = QtWidgets.QLineEdit(ExportForm)
        self.status_filePath.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_filePath.sizePolicy().hasHeightForWidth())
        self.status_filePath.setSizePolicy(sizePolicy)
        self.status_filePath.setObjectName("status_filePath")
        self.gridLayout.addWidget(self.status_filePath, 0, 0, 1, 2)
        self.pbn_Export = QtWidgets.QPushButton(ExportForm)
        self.pbn_Export.setObjectName("pbn_Export")
        self.gridLayout.addWidget(self.pbn_Export, 2, 2, 1, 1)
        self.pbn_FileExplorer = QtWidgets.QPushButton(ExportForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbn_FileExplorer.sizePolicy().hasHeightForWidth())
        self.pbn_FileExplorer.setSizePolicy(sizePolicy)
        self.pbn_FileExplorer.setMaximumSize(QtCore.QSize(120, 30))
        self.pbn_FileExplorer.setObjectName("pbn_FileExplorer")
        self.gridLayout.addWidget(self.pbn_FileExplorer, 0, 2, 1, 1)

        self.retranslateUi(ExportForm)
        QtCore.QMetaObject.connectSlotsByName(ExportForm)

    def retranslateUi(self, ExportForm):
        _translate = QtCore.QCoreApplication.translate
        ExportForm.setWindowTitle(_translate("ExportForm", "Form"))
        self.pbn_Export.setText(_translate("ExportForm", "Export Tags"))
        self.pbn_FileExplorer.setText(_translate("ExportForm", "File Path..."))
