# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5_DesignFile_ImportTarget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Import_Target(object):
    def setupUi(self, Import_Target):
        Import_Target.setObjectName("Import_Target")
        Import_Target.resize(280, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Import_Target.sizePolicy().hasHeightForWidth())
        Import_Target.setSizePolicy(sizePolicy)
        Import_Target.setMinimumSize(QtCore.QSize(280, 550))
        Import_Target.setMaximumSize(QtCore.QSize(3000, 3000))
        self.gridLayout = QtWidgets.QGridLayout(Import_Target)
        self.gridLayout.setObjectName("gridLayout")
        self.pbn_write = QtWidgets.QPushButton(Import_Target)
        self.pbn_write.setObjectName("pbn_write")
        self.gridLayout.addWidget(self.pbn_write, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.lst_chkboxes = QtWidgets.QListWidget(Import_Target)
        self.lst_chkboxes.setObjectName("lst_chkboxes")
        self.gridLayout.addWidget(self.lst_chkboxes, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(Import_Target)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Import_Target)
        QtCore.QMetaObject.connectSlotsByName(Import_Target)

    def retranslateUi(self, Import_Target):
        _translate = QtCore.QCoreApplication.translate
        Import_Target.setWindowTitle(_translate("Import_Target", "Select Export File Path"))
        self.pbn_write.setText(_translate("Import_Target", "PushButton"))
        self.label.setText(_translate("Import_Target", "Available Programs"))
