# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5_DesignFile_MessageView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTable(object):
    def setupUi(self, EditTable):
        EditTable.setObjectName("EditTable")
        EditTable.resize(932, 685)
        self.tab_faults = QtWidgets.QWidget()
        self.tab_faults.setObjectName("tab_faults")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_faults)
        self.gridLayout.setObjectName("gridLayout")
        self.tbl_faults = QtWidgets.QTableWidget(self.tab_faults)
        self.tbl_faults.setAlternatingRowColors(True)
        self.tbl_faults.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_faults.setObjectName("tbl_faults")
        self.tbl_faults.setColumnCount(2)
        self.tbl_faults.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_faults.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_faults.setHorizontalHeaderItem(1, item)
        self.tbl_faults.horizontalHeader().setDefaultSectionSize(120)
        self.tbl_faults.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_faults.horizontalHeader().setStretchLastSection(True)
        self.tbl_faults.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tbl_faults, 1, 0, 1, 1)
        self.groupbox_Fault = QtWidgets.QGroupBox(self.tab_faults)
        self.groupbox_Fault.setTitle("")
        self.groupbox_Fault.setObjectName("groupbox_Fault")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupbox_Fault)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_reload = QtWidgets.QPushButton(self.groupbox_Fault)
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout.addWidget(self.btn_reload)
        self.gridLayout.addWidget(self.groupbox_Fault, 0, 0, 1, 1)
        EditTable.addTab(self.tab_faults, "")
        self.tab_msg = QtWidgets.QWidget()
        self.tab_msg.setObjectName("tab_msg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_msg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tbl_msg = QtWidgets.QTableWidget(self.tab_msg)
        self.tbl_msg.setAlternatingRowColors(True)
        self.tbl_msg.setColumnCount(2)
        self.tbl_msg.setObjectName("tbl_msg")
        self.tbl_msg.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_msg.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_msg.setHorizontalHeaderItem(1, item)
        self.tbl_msg.horizontalHeader().setDefaultSectionSize(120)
        self.tbl_msg.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_msg.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tbl_msg, 1, 0, 1, 1)
        self.groupbox_Message = QtWidgets.QGroupBox(self.tab_msg)
        self.groupbox_Message.setTitle("")
        self.groupbox_Message.setObjectName("groupbox_Message")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupbox_Message)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(786, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_reload_2 = QtWidgets.QPushButton(self.groupbox_Message)
        self.btn_reload_2.setObjectName("btn_reload_2")
        self.horizontalLayout_2.addWidget(self.btn_reload_2)
        self.gridLayout_2.addWidget(self.groupbox_Message, 0, 0, 1, 1)
        EditTable.addTab(self.tab_msg, "")

        self.retranslateUi(EditTable)
        EditTable.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(EditTable)

    def retranslateUi(self, EditTable):
        _translate = QtCore.QCoreApplication.translate
        EditTable.setWindowTitle(_translate("EditTable", "TabWidget"))
        self.tbl_faults.setSortingEnabled(False)
        item = self.tbl_faults.horizontalHeaderItem(0)
        item.setText(_translate("EditTable", "FaultID"))
        item = self.tbl_faults.horizontalHeaderItem(1)
        item.setText(_translate("EditTable", "Message"))
        self.btn_reload.setText(_translate("EditTable", "Reload"))
        EditTable.setTabText(EditTable.indexOf(self.tab_faults), _translate("EditTable", "Faults"))
        item = self.tbl_msg.horizontalHeaderItem(0)
        item.setText(_translate("EditTable", "MessageID"))
        item = self.tbl_msg.horizontalHeaderItem(1)
        item.setText(_translate("EditTable", "Message"))
        self.btn_reload_2.setText(_translate("EditTable", "Reload"))
        EditTable.setTabText(EditTable.indexOf(self.tab_msg), _translate("EditTable", "Messages"))
