# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5_DesignFile_MessageView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTable(object):
    def setupUi(self, EditTable):
        EditTable.setObjectName("EditTable")
        EditTable.resize(936, 484)
        self.tab_faults = QtWidgets.QWidget()
        self.tab_faults.setObjectName("tab_faults")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_faults)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_faults)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        EditTable.addTab(self.tab_faults, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        EditTable.addTab(self.tab_2, "")

        self.retranslateUi(EditTable)
        EditTable.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(EditTable)

    def retranslateUi(self, EditTable):
        _translate = QtCore.QCoreApplication.translate
        EditTable.setWindowTitle(_translate("EditTable", "TabWidget"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("EditTable", "FaultID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("EditTable", "Message"))
        EditTable.setTabText(EditTable.indexOf(self.tab_faults), _translate("EditTable", "Faults"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("EditTable", "MessageID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("EditTable", "Message"))
        EditTable.setTabText(EditTable.indexOf(self.tab_2), _translate("EditTable", "Messages"))
